---
idensys_vhost_name: idensys.example.com
smtp_server: localhost
error_mail_to: logs@example.org
email_noreply: noreply@example.com

  # Maven version
idensys_version: 1.0.1-SNAPSHOT
idensys_proxy:
  # encrypted
  private_key: "{{ lookup('file', inventory_dir+'/saml_cert/idensys.key') }}"
  certificate: "{{ lookup('file', inventory_dir+'/saml_cert/idensys.crt')}}"
  # https://eid.digidentity-preproduction.eu/hm/eh19/metadata
  idp_metadata_feed: classpath:saml/idensys.metadata.saml.xml
  # https://engine.test2.surfconext.nl/authentication/sp/metadata
  sp_metadata_feed: classpath:saml/eb.sp.metadata.xml
  # value of the keyName in the KeyDescriptor
  key_name: whatever-configurable
  # Format: urn:etoegang:DV:<OIN>:entities:0001
  # To get an <OIN> from a KVK number use:
  # OIN = "00000003" + <KVK number> "0000"
  enity_id: urn:etoegang:DV:00000003kkkkkkkk0000:entities:0001
  # Format: urn:etoegang:DV:<OIN>:services:0001
  service_id: urn:etoegang:DV:00000003kkkkkkkk0000:services:0001
  service_name: Test Service
  organization_name: ACME Inc.
  organization_disaplay_name: ACME
  organization_url: http://www.example.org
  technical_contact_givenname: John
  technical_contact_surname: Doe
  technical_contact_email: jorn.doe@acme.org
  technical_contact_telephone: 555-12345
