---
- name: Install haveged
  yum: name={{ item }} state=present
  with_items:
    - haveged
  tags: haveged

- name: enable haveged
  service: name={{ item }} enabled=yes state=started
  with_items:
       - haveged
  notify:
    - restart haveged
