---
- hosts: idensys
  become: true
  gather_facts: yes
  roles:
    - { role: initial, tags: initial }
    - { role: haveged, tags: haveged }
    - { role: httpd, tags: httpd }
    - { role: java, tags: java }
    - { role: idensys, tags: idensys }
